[tool.poetry]
name = "bridge-service"
version = "0.1.0"
description = "Bridge service between RabbitMQ and Dashboard"
authors = ["Your Name <your.email@example.com>"]
#packages = [{include = "bridge_service", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.104.0"
uvicorn = "^0.23.2"
pika = "^1.3.2"
python-dotenv = "^1.0.0"
pydantic = "^2.4.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "bridge_service:main"